name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "423ec6b71480f41e45d716dae60a626991694e27d0436d3cd2c9d356a0a9a8a6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
