name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aad648c9a74b42ceeb3b77be506422973830d60565ed2664b65cc5cc1d8f634"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
