name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ca119f3f5f8435a6b5b847a85936b71f77a5064006ec536532b5bb82273b730"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
