name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbdc4e55e4c0644648a26413af0bb29c0f0b4ec4f326045129112a0fec2c5139"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
