name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c19bbafc018fddb540e6cc585286fa2ea31a05abe207abc7b3ff1ec281307c78"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
