name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92ab469ae4d9814245f048ce0210f7a053b05c40c1d7d260be4b269be3548e25"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
