name = "Lunarie-2"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d5dd22910e98edcbfe6b1fc9d1aae1eb7a5567e0a8389dbb07868bd0a6bdeef"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
